/*
 * cmd_enum.h
 *
 *  Created on: 12 окт. 2019 г.
 *      Author: shishqa
 */

#ifndef CMD_ENUM_H_
#define CMD_ENUM_H_


#define DEF_CMD( opcode, name, type, len, n_args, stack_args, code ) \
  CMD_##name = opcode,

enum
{
    //----------------------------------
    // autogenerated
    //----------------------------------
    #include "cmd_defines.h"
    //----------------------------------
    // autogenerated
    //----------------------------------

    CMD_MAX
};

#undef DEF_CMD

#pragma pack(1)
struct Argument
{
	char int_param : 1;
	char reg_param : 1;
	char mem_param : 1;
	char sum_param : 1;
	char nop	   : 4;
	char reg       ;
	Elem_t val     ;
};
#pragma pack()


#endif /* CMD_ENUM_H_ */
